export type AllExpertise =
  | "Gym"
  | "Technology"
  | "Physics"
  | "Chemistry"
  | "Biology"
  | "Mathematics"
  | "Computer Science"
  | "Art"
  | "Music"
  | "Literature"
  | "Business"
  | "Economics"
  | "History"
  | "Geography"
  | "Philosophy"
  | "Religion"
  | "Psychology"
  | "Sociology"
  | "Political Science"
  | "Law"
  | "Medicine"
  | "Psychiatry"
  | "Education"
  | "Architecture"
  | "Engineering"
  | "Agriculture";